- docs/openapiv2/apidocs.swagger.json
- openfga/v1/authzmodel.proto
- openfga/v1/openfga.proto
- openfga/v1/openfga_service.proto
You can ignore the `swagger.json` file when reviewing this PR, as it's generated by `buf generate`.
- Add a few examples in the proto files
- Whenever we have a mix of `min_len/max_len` and `pattern` validation, remove the `min_len` and `max_len` in favor of an updated pattern that includes the length. See https://github.com/envoyproxy/protoc-gen-validate/issues/79
- Both `store_id` and `authorization_model_id` are generated with https://github.com/oklog/ulid, which generates 26 characters. Change the validation for these fields
n/a
> chore: change validation patterns

- .gitignore
- README.md
- buf.gen.yaml
These changes introduce Go source code generation plugins to the `buf.gen.yaml` file so that developers can build the sources from the protobufs for development and testing. Any source code generated from the protobufs is ignored in the `.gitignore` file because the goal is to import the generated sources from the Buf Remote Registry instead. This is just to assist with local development workflows where you want to test protobuf changes before publishing a new version.
> chore: add Go source code generation plugins for local development

- openfga/v1/openfga.proto
- openfga/v1/openfga_service.proto
From Slack:
```
Writing/checking against our github tuples is now throwing and invalid regex error:
rpc error: code = InvalidArgument desc = invalid CheckRequest.TupleKey: embedded message failed validation | caused by: invalid TupleKey.Object: value does not match regex pattern \"^[^\\\\s]{,256}$\"
But it’s triggering for checks as simple as:
curl -s -X POST http://localhost:8080/stores/$STORE_ID/check -d '{ "tuple_key": { "user": "anne", "relation": "maintainer", "object": "repo:a" } }'
repo:a should be a valid object
```
> fix: quantifiers in regexes

- openfga/v1/openfga_service.proto
The correct create_store status code is 201, not 200.
- Close https://github.com/openfga/api/issues/13
> fix: correct create_store http status code

- .github/workflows/push.yaml
This changes our `push` action so that we push new Buf modules to the Buf Registry only on changes to protobuf files. If no doc or protobuf files have changed that the Buf Registry depends on, then the push action will be skipped.
> ci: only push new Buf module when relevant .proto files have changed

- docs/openapiv2/apidocs.swagger.json
- openfga/v1/errors_ignore.proto
- openfga/v1/openfga_service.proto
This PR adds the ListObjects (and StreamedListObjects) API definitions as described in https://github.com/openfga/rfcs/pull/3 to the OpenFGAService.
https://github.com/openfga/roadmap/issues/8
[Approved RFC](https://github.com/openfga/rfcs/blob/main/20220714-listObjects-api.md)
https://github.com/openfga/rfcs/pull/3
Closes https://github.com/openfga/api/issues/10
I will add doc to openfga.dev once the implementation is in review in the openfga/openfga repository.
> feat: add ListObjects API definitions to the OpenFGAService

- openfga/v1/openfga.proto
This adds a protobuf definition for Object types in the OpenFGA API. This will make it easier to pass around objects instead of passing around OpenFGA objects formatted as strings such as `document:1`. I believe this will make our code easier to manage and read.
> chore: add Object definition to openfga.v1 protobuf API

- buf.lock
To fix this: 
```
Failure: buf.build/googleapis/googleapis:80720a488c9a414bb8d4a9f811084989: does not exist
```
> fix: update buf.lock

- openfga/v1/authzmodel.proto
- openfga/v1/openfga_service.proto
Adds the `Relation` type to the protobuf definitions so we can re-use it throughout our code. This will make things more tidy and elegant on the backend where we store a `map[string]*openfgapb.TypeDefinition`. Instead, we can now store `map[string]*openfgapb.Relation` and use that in places, which will reduce the duplication of indexing into two maps all over the place and will allow us to pass around a Relation object where appropriate.
> chore: add Relation type to protobuf definitions for reusability

- docs/openapiv2/apidocs.swagger.json
- openfga/v1/openfga_service.proto
This PR introduces length restrictions on the `user`, `relation` and `type` parameters of the ListObjects and StreamedListObjects APIs.
The validations for `user` and `relation` are the same as the ones for `TupleKey.user` and `TupleKey.relation`. 
The validation for `type` is the same as the one for `Object.type`.
> fix: listobjects validation of parameters

- docs/openapiv2/apidocs.swagger.json
- openfga/v1/openfga.proto
In Check, we may want to include the contextual tuple field, but with no contextual tuples as in:
```
{
"authorization_model_id": "01GFVBCAW5QAJVWRMDC82H4Z7D",
"tuple_key": {
"object": "repo:openfga/openfga",
"relation": "reader",
"user": "anne"
},
"contextual_tuples": {
"tuple_keys": null
}
}
```
This PR is the change that allows us to do this.
Why do this? It helps in automation.
> refactor: remove min from contextual tuples

- buf.gen.yaml
- docs/openapiv2/apidocs.swagger.json
- openfga/v1/openfga_service.proto
You can paste the generated Swagger file here to view it: https://editor.swagger.io/
You should see this 
If we want to be even _more_ specific (e.g. Read requires `tupleKey.object` but not the others), we need to introduce specific `TupleKey` messages for the API.
> chore: document required fields in requests with a body

- docs/openapiv2/apidocs.swagger.json
- openfga/v1/openfga_service.proto
Need to specify list object user field must be non empty string.  Currently, non-specified user field are interpreted as empty string.  With the change, ListObject with payload
```
{
"type": "resource",
"relation": "reader"
}
```
will return 
```
{
"code": "validation_error",
"message": "invalid ListObjectsRequest.User: value length must be between 1 and 512 bytes, inclusive"
}
```
Close https://github.com/openfga/api/issues/58
> fix: list object must have user define

- docs/openapiv2/apidocs.swagger.json
- openfga/v1/openapi.proto
Update contact section so that it points to the correct email instead of only the website.
Close https://github.com/openfga/openfga.dev/issues/288
> fix: update contact to point to email

- .github/workflows/push.yaml
- .github/workflows/review.yaml
- buf.gen.yaml
The generated `go.mod` is this:
```
module go.buf.build/openfga/go/openfga/api
go 1.20
require (
github.com/envoyproxy/protoc-gen-validate v0.10.1
github.com/grpc-ecosystem/grpc-gateway/v2 v2.15.2
google.golang.org/genproto v0.0.0-20230327215041-6ac7f18bb9d5
google.golang.org/grpc v1.54.0
google.golang.org/protobuf v1.30.0
)
require (
github.com/golang/protobuf v1.5.3 // indirect
golang.org/x/net v0.8.0 // indirect
golang.org/x/sys v0.6.0 // indirect
golang.org/x/text v0.8.0 // indirect
)
```
> chore: update versions

- docs/openapiv2/apidocs.swagger.json
- openfga/v1/authzmodel.proto
- openfga/v1/openfga_service.proto
Because we want users to explicitly send 1.1. 
I'm not sure when we want to merge this, this is a breaking change ⚠️
> feat: make schema version a required field

- docs/openapiv2/apidocs.swagger.json
- openfga/v1/openfga_service.proto
Hides the unimplemented API endpoint to `UpdateStore` until we have an implementation for it.
@andreadistefano - if you end up implementing this API endpoint, please cross-reference.
#74
> chore: hide unimplemented API definitions

- buf.gen.yaml
- buf.lock
The Buf team announced a while back that they are deprecating support for the alpha implementation of the Buf Remote Plugins in favor of a more stable and officially maintained public plugins registry. For more information see https://buf.build/docs/bsr/remote-plugins/migrating-from-alpha/
This PR swaps our remote plugins to use the new public plugins provided by Buf, and this eliminates the deprecation warnings that were emitted.
> chore: swap deprecated features and switch to official public plugins

- .github/workflows/review.yaml
All the PRs targetting `feat/abac` fail with `breaking change`, even though the breaking change is against `main` not `feat/abac`
> chore: run workflow against base branch instead of always main

- proto/go.mod
Fix module definition in go.mod.
Previous PR introduced go.mod module definition that's incorrect. This PR corrects the module definition in go.mod.
[issue-949](https://github.com/openfga/openfga/issues/946)
> Fix: go.mod module definition introduced conceptual tuples

- proto/go.mod
- proto/go.sum
The new version of `grpc-gateway` introduces some linter concerns with deprecation notices whose changes incur some non-standard replacements. This PR reverts to `v2.19.1` of grpc-gateway until we can address that deprecation notice properly.
https://github.com/openfga/openfga/pull/1642
> chore(deps): downgrade grpc-gateway until we can migrate deprecated

- .github/CODEOWNERS
- docs/openapiv2/apidocs.swagger.json
- openfga/v1/openfga_service.proto
- proto/openfga/v1/openfga_service.pb.go
Corrects higher to lower on the MINIMIZE_LATENCY doc string
> doc: correct consistency reference in doc string

- .github/workflows/push.yaml
- .github/workflows/review.yaml
- openfga/v1/authzmodel.proto
- openfga/v1/openapi.proto
- openfga/v1/openfga.proto
- openfga/v1/openfga_service.proto
Instead we will use the version that correlates to the action version, so an action upgrade means that we will be running that version of buf in CI. The default for the `version` parameter is changed every buf/buf-setup-action releases, so an upgrade of the action is an upgrade of buf.
Looking through the git blame I don't see a reason why we're pinning buf, it seems to be in place since this repo was started and then sporadically updated.
> ci: don't pin version of buf

- .github/workflows/push.yaml
- .github/workflows/review.yaml
Merges `main` into `feat/stronger-consistency-options` as that branch has branch protection enabled, so we can't push
> Merge main int feat/stronger-consistency-options

- .githooks/pre-commit
- Makefile
- README.md
When updating a proto file last week, I forgot to update the docs. We have a github action check for this scenario but it's annoying to have to wait for such a simple fix.
This PR adds a ~non~ blocking pre-commit hook to remind the author if the docs or generated files need updating.
It does the following:
1. If an update to a `.proto` file is being committed
2. Check if the `/docs` and `/proto/openfga/` folder are also being committed
3. If `/docs` and `/proto/openfga/` **are** being committed, hook exits successfully
4. If one of the two above is not being committed, ~remind the author to update the docs but also exit successfully (non-blocking)~ block the commit and remind the author to update the generated files.
https://github.com/user-attachments/assets/c9e710f2-47f9-4d78-ba9e-947879 …
> CI: pre-commit check for generated files

- .github/workflows/review.yaml
The old one has been deprecated and is causing CI errors as can be seen here: https://github.com/openfga/api/actions/runs/12349913805/job/34484604530?pr=211
Includes:
* https://github.com/swaggerexpert/swagger-editor-validate/releases/tag/v1.4.0
* https://github.com/swaggerexpert/swagger-editor-validate/releases/tag/v1.4.1
Full list of changes: https://github.com/swaggerexpert/swagger-editor-validate/compare/v1.3.2...v1.4.1 (also can be confirmed via https://github.com/swaggerexpert/swagger-editor-validate/compare/65266f9d3147e446b96af879fd317ce6079529ea...v1.4.1)
The error:
The commit that fixes it:
https://github.com/swaggerexpert/swagger-editor-validate/commit/ff8ba2b3a3aac5a7c42749abf94fc5cb5f1e4737
Unblocks: https://github.com/openfga/api/pull/211
> chore(ci): changed the validate swagger ci tag
